name: github_action_pipeline1     #Optional - The name of the workflow as it will appear in the "Actions" tab of the GitHub
on: workflow_dispatch             #Required - Specifies the trigger for this workflow. 
jobs:                             #Required - Groups together all the jobs that run in the github_action_pipeline1 workflow defined above. 
  my-job:                         #Required - Defines a job named my-job. The child keys will define properties of the job.
    runs-on: ubuntu-latest        #Required - Configures the job to run on the latest version of an Ubuntu Linux runner. 
    steps:                        #Required - Groups together all the steps that run in the my-job job defined above. 
      - name: my-step-1 
        run: echo "Hello World!"    #Optional - The run keyword tells the job to execute a command on the runner.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v1.34.2
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Deploy'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100' #Set start and end dates for planned time - "start_date":"2023-04-25 16:54:00","end_date":"2023-04-25 16:58:00"
          timeout: '3600'
  my-job2:                         #Required - Defines a job named my-job. The child keys will define properties of the job.
    runs-on: ubuntu-latest        #Required - Configures the job to run on the latest version of an Ubuntu Linux runner. 
    steps:                        #Required - Groups together all the steps that run in the my-job job defined above. 
      - name: my-step-2 
        run: echo "Hello World!"    #Optional - The run keyword tells the job to execute a command on the runner.
